### ISSUE TITLE
Add PMD as part of the build process

### ISSUE THREAD

**Issue by NewestUser** [NewestUser/imen#11]
I would like to have [PMD](https://maven.apache.org/plugins/maven-pmd-plugin/) integrated into the build process.

This would forbid merging code that does not comply with common guidelines. Example: if it contains unused variables/ imports or etc..

Here is the [setup guide](https://maven.apache.org/plugins/maven-pmd-plugin/usage.html).

NOTE: travis should fail the build if the maven PMD check does not pass.

**Comment by NewestUser** [comment]
Adding @IvoStaynov  @rositsabodurova for visibility

**Comment by dahmedov** [comment]
The task is done.
