### ISSUE TITLE
Add a test code coverage threshold for merging PRs

### ISSUE THREAD

**Issue by NewestUser** [NewestUser/imen#12]
I would like to have a certain percent of test coverage for the project.

In order to enforce this we can use a code coverage tool like [JaCoCo](https://www.mkyong.com/maven/maven-jacoco-code-coverage-example/) which can be run by travis and fail builds that introduce code without a decent amount of test coverage.

**Comment by NewestUser** [comment]
Adding @IvoStaynov @rositsabodurova @dahmedov  for visibility

**Comment by b0b3t0** [comment]
Done.
