### ISSUE TITLE
Integrate Travis CI

### ISSUE THREAD

**Issue by NewestUser** [NewestUser/imen#2]
I would like to add an integration with Travis.
This way we can enforce builds upon PR merges

Here are the travis [docs](https://docs.travis-ci.com/user/tutorial/) and a [random video tutorial](https://www.youtube.com/watch?v=Uft5KBimzyk).

**Comment by NewestUser** [comment]
@dahmedov you can start integrating travis into the project.

Travis is an external CI/CD tool. It can be used to run tests perform code quality checks and etc.

In order to integrate it with our project you can try setting it up first on your fork (at least I think so).
If that works you can open a PR and merge it.

To get started login into travis and configure your imen fork.
You can follow the docs. https://docs.travis-ci.com/user/tutorial/

If you have any questions feel free to ping me here on PM.

I am adding @rositsabodurova @IvoStaynov  for visibility.

**Comment by dahmedov** [comment]
Done
