### ISSUE TITLE
Research how Google search indexing works and can we improve indexing of the calendar

### ISSUE THREAD

**Issue by NewestUser** [NewestUser/imen#21]
Research how Google Search indexing works and figure out if it is possible to apply some tricks so that https://imen-bg.herokuapp.com/ can appear in search results.

The scope of this issue is to come with an outcome and possibly some steps we can take to improve SEO (search engine optimization).

Here are some articles regarding this (I haven't red them just did a quick search, they are optional but can serve as a starter)
- [Search Engine Optimization (SEO) Starter Guide](https://support.google.com/webmasters/answer/7451184?hl=en)
- [beginners-guide-to-seo](https://moz.com/beginners-guide-to-seo)
- [top-10-killer-tips-to-increase-google-crawl-rate.html](https://www.shoutmeloud.com/top-10-killer-tips-to-increase-google-crawl-rate.html)
- [How to Get Google to Instantly Index Your New Website](https://neilpatel.com/blog/google-index/)

**Comment by rositsabodurova** [comment]
We need to make a redesign of the home page of the app. Currently we do not have any h1 tag included. H1 tag is the essential prerequisite in order to be found by the search engine. We should include the key words associated with the content of our site. Apart from that, we must add additional content, as currently it does not have any other except for the date/converted date.
After considering the site somewhat done, we can take more advanced SEO steps.

**Comment by NewestUser** [comment]
Thanks for the research.
Here is a sample [Online Clock](http://www.clocktab.com/) that utilizes the things that you mention.

Here are also some [search terms](https://trends.google.com/trends/explore?geo=BG&q=%D1%81%D1%82%D0%B0%D1%80%D0%BE%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8,%D0%BA%D0%B0%D0%BB%D0%B5%D0%BD%D0%B4%D0%B0%D1%80,%D0%B4%D1%80%D0%B5%D0%B2%D0%B5%D0%BD,%D0%B4%D1%80%D0%B5%D0%B2%D0%BD%D0%BE%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8,%D0%BF%D1%80%D0%B0%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8) that from top of my head:
From those defensively **календар** is the most trending word. 
Words like **прабългарски** and **древнобългарски** are not really searched but that might be a plus for us as we won't have any competition on those.

**Comment by NewestUser** [comment]
I am closing this issue as the scope of it was to do some research and come up with next steps.
This will be implemented in [Issue 22](https://github.com/NewestUser/imen/issues/22)
