### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by NewestUser** [NewestUser/imen#22]
The scope of this story is to add some fields in the HTML so that search engines can better index the website.
Adding title, keywords and other meta info to the site will help with SEO.
Any other ideas are more than welcomed.

Some research we did on this can be found in [Issue 21](https://github.com/NewestUser/imen/issues/21).

**Comment by IvoStaynov** [comment]
I have added keywords, description and distribution to the HTML file.
Is [google site verification](https://support.google.com/webmasters/answer/9008080?hl=en) a good idea for SEO ?

**Comment by NewestUser** [comment]
It seems that google site verification is the next step that we should take. I didn't even know that such a thing exists. Congrats on finding that! I have logged an issue #24 for that.
