### ISSUE TITLE
Implement date conversion between current time and Bulgarian Time

### ISSUE THREAD

**Issue by NewestUser** [NewestUser/imen#3]
I would like to be able to determine the current time according the Bulgarian Calendar.

For this to happen the algorithm for converting needs to be figured out. A sample implementation can be found [here](https://github.com/abozhilov/bgcalendar).

**Comment by NewestUser** [comment]
As a first variant of the implementation it is Ok to exclude leap years.

Here are some example conversions in the following format: `yyyy-mm-dd` (this is based on the [converter](http://calendar.samoistina.com/))

|Gregorian date|Bulgarian date|
|---|---|
|2010-01-01| 10 Алем, 6778 Барс|
|2011-01-01|10 Алем, 6779 Дван|
|2011-02-01|10 Тутом, 6779 Дван|
|2011-02-02|11 Тутом, 6779|


The month names can be found [here](https://github.com/abozhilov/bgcalendar/blob/master/bgcalendar.js#L18) and the year types can be found [here](https://github.com/abozhilov/bgcalendar/blob/master/bgcalendar.js#L32).

The number of years that the Gregorian calendar differs from the Bulgarian is **4768**

The number of days in the months in the Bulgarian calendar go in the following order:

31+30+30+31+30+30+31+30+30+31+30+30 (which equals in total 364, add 1 more for leap yers and we get 365)

**Comment by NewestUser** [comment]
@rositsabodurova @IvoStaynov feel free to write any outcome that might help understand how the calendar is supposed to be implemented.

**Comment by NewestUser** [comment]
|Gregorian Day of Year  |Gregorian Day of Month|Gregorian Month     |Bulgarian Day of Year  |Bulgarian Day of Month|Bulgarian Month| Notes |
|---                    |---                  |---                  |---                    |---                   |---            |---    |
|1                      |1                    |January              |                       |10     |1    | |
|2                      |2                    |January              |                       |11     |1    | |
|3                      |3                    |January              |                       |12     |1    | |
|4                      |4                    |January              |                       |13     |1    | |
|5                      |5                    |January              |                       |14     |1    | |
|6                      |6                    |January              |                       |15     |1    | |
|7                      |7                    |January              |                       |16     |1    | |
|8                      |8                    |January              |                       |17     |1    | |
|9                      |9                    |January              |                       |18     |1    | |
|10                     |10                   |January              |                       |19     |1    | |
|11                     |11                   |January              |                       |20     |1    | |
|12                     |12                   |January              |                       |21     |1    | |
|13                     |13                   |January              |                       |22     |1    | |
|14                     |14                   |January              |                       |23     |1    | |
|15                     |15                   |January              |                       |24     |1    | |
|16                     |16                   |January              |                       |25     |1    | |
|17                     |17                   |January              |                       |26     |1    | |
|18                     |18                   |January              |                       |27     |1    | |
|19                     |19                   |January              |                       |28     |1    | |
|20                     |20                   |January              |                       |29     |1    | |
|21                     |21                   |January              |                       |30     |1    | |
|22                     |22                   |January              |                       |31     |1    | |
|23                     |23                   |January              |                       |1      |2    | |
|24                     |24                   |January              |                       |2      |2    | |
|25                     |25                   |January              |                       |3      |2    | |
|26                     |26                   |January              |                       |4      |2    | |
|27                     |27                   |January              |                       |5      |2    | |
|28                     |28                   |January              |                       |6      |2    | |
|29                     |29                   |January              |                       |7      |2    | |
|30                     |30                   |January              |                       |8      |2    | |
|31                     |31                   |January              |                       |9      |2    | |
|32                     |1                    |February             |                       |10     |2    | |
|33                     |2                    |February             |                       |11     |2    | |
|34                     |3                    |February             |                       |12     |2    | |
|35                     |4                    |February             |                       |13     |2    | |
|36                     |5                    |February             |                       |14     |2    | |
|37                     |6                    |February             |                       |15     |2    | |
|38                     |7                    |February             |                       |16     |2    | |
|39                     |8                    |February             |                       |17     |2    | |
|40                     |9                    |February             |                       |18     |2    | |
|41                     |10                   |February             |                       |19     |2    | |
|42                     |11                   |February             |                       |20     |2    | |
|43                     |12                   |February             |                       |21     |2    | |
|44                     |13                   |February             |                       |22     |2    | |
|45                     |14                   |February             |                       |23     |2    | |
|46                     |15                   |February             |                       |24     |2    | |
|47                     |16                   |February             |                       |25     |2    | |
|48                     |17                   |February             |                       |26     |2    | |
|49                     |18                   |February             |                       |27     |2    | |
|50                     |19                   |February             |                       |28     |2    | |
|51                     |20                   |February             |                       |29     |2    | |
|52                     |21                   |February             |                       |30     |2    | |
|53                     |22                   |February             |                       |1      |3    | |
|54                     |23                   |February             |                       |2      |3    | |
|55                     |24                   |February             |                       |3      |3    | |
|56                     |25                   |February             |                       |4      |3    | |
|57                     |26                   |February             |                       |5      |3    | |
|58                     |27                   |February             |                       |6      |3    | |
|59                     |28                   |February             |                       |7      |3    | |
|60 (in leap only)      |29                   |February             |                       |8      |3    | Nothing special about this day in the BG calendar. The leap year is added as day zero of month 7 |
|61 (-1 for non leap)   |1                    |March                |                       |9      |3    | |
|62 (-1 for non leap)   |2                    |March                |                       |10     |3    | |
|63 (-1 for non leap)   |3                    |March                |                       |11     |3    | |
|64 (-1 for non leap)   |4                    |March                |                       |12     |3    | |
|65 (-1 for non leap)   |5                    |March                |                       |13     |3    | |
|66 (-1 for non leap)   |6                    |March                |                       |14     |3    | |
|67 (-1 for non leap)   |7                    |March                |                       |15     |3    | |
|68 (-1 for non leap)   |8                    |March                |                       |16     |3    | |
|69 (-1 for non leap)   |9                    |March                |                       |17     |3    | |
|70 (-1 for non leap)   |10                   |March                |                       |18     |3    | |
|71 (-1 for non leap)   |11                   |March                |                       |19     |3    | |
|72 (-1 for non leap)   |12                   |March                |                       |20     |3    | |
|73 (-1 for non leap)   |13                   |March                |                       |21     |3    | |
|74 (-1 for non leap)   |14                   |March                |                       |22     |3    | |
|75 (-1 for non leap)   |15                   |March                |                       |23     |3    | |
|76 (-1 for non leap)   |16                   |March                |                       |24     |3    | |
|77 (-1 for non leap)   |17                   |March                |                       |25     |3    | |
|78 (-1 for non leap)   |18                   |March                |                       |26     |3    | |
|79 (-1 for non leap)   |19                   |March                |                       |27     |3    | |
|80 (-1 for non leap)   |20                   |March                |                       |28     |3    | |
|81 (-1 for non leap)   |21                   |March                |                       |29     |3    | |
|82 (-1 for non leap)   |22                   |March                |                       |30     |3    | |
|83 (-1 for non leap)   |23                   |March                |                       |1      |4    | |
|84 (-1 for non leap)   |24                   |March                |                       |2      |4    | |
|85 (-1 for non leap)   |25                   |March                |                       |3      |4    | |
|86 (-1 for non leap)   |26                   |March                |                       |4      |4    | |
|87 (-1 for non leap)   |27                   |March                |                       |5      |4    | |
|88 (-1 for non leap)   |28                   |March                |                       |6      |4    | |
|89 (-1 for non leap)   |29                   |March                |                       |7      |4    | |
|90 (-1 for non leap)   |30                   |March                |                       |8      |4    | |
|91 (-1 for non leap)   |31                   |March                |                       |9      |4    | |
|92 (-1 for non leap)   |1                    |April                |                       |10     |4    | |
|93 (-1 for non leap)   |2                    |April                |                       |11     |4    | |
|94 (-1 for non leap)   |3                    |April                |                       |12     |4    | |
|95 (-1 for non leap)   |4                    |April                |                       |13     |4    | |
|96 (-1 for non leap)   |5                    |April                |                       |14     |4    | |
|97 (-1 for non leap)   |6                    |April                |                       |15     |4    | |
|98 (-1 for non leap)   |7                    |April                |                       |16     |4    | |
|99 (-1 for non leap)   |8                    |April                |                       |17     |4    | |
|100(-1 for non leap)   |9                    |April                |                       |18     |4    | |
|101(-1 for non leap)   |10                   |April                |                       |19     |4    | |
|102(-1 for non leap)   |11                   |April                |                       |20     |4    | |
|103(-1 for non leap)   |12                   |April                |                       |21     |4    | |
|104(-1 for non leap)   |13                   |April                |                       |22     |4    | |
|105(-1 for non leap)   |14                   |April                |                       |23     |4    | |
|106(-1 for non leap)   |15                   |April                |                       |24     |4    | |
|107(-1 for non leap)   |16                   |April                |                       |25     |4    | |
|108(-1 for non leap)   |17                   |April                |                       |26     |4    | |
|109(-1 for non leap)   |18                   |April                |                       |27     |4    | |
|110(-1 for non leap)   |19                   |April                |                       |28     |4    | |
|111(-1 for non leap)   |20                   |April                |                       |29     |4    | |
|112(-1 for non leap)   |21                   |April                |                       |30     |4    | |
|113(-1 for non leap)   |22                   |April                |                       |31     |4    | |
|114(-1 for non leap)   |23                   |April                |                       |1      |5    | |
|115(-1 for non leap)   |24                   |April                |                       |2      |5    | |
|116(-1 for non leap)   |25                   |April                |                       |3      |5    | |
|117(-1 for non leap)   |26                   |April                |                       |4      |5    | |
|118(-1 for non leap)   |27                   |April                |                       |5      |5    | |
|119(-1 for non leap)   |28                   |April                |                       |6      |5    | |
|120(-1 for non leap)   |29                   |April                |                       |7      |5    | |
|121(-1 for non leap)   |30                   |April                |                       |8      |5    | |
|122(-1 for non leap)   |1                    |May                  |                       |9      |5    | |
|123(-1 for non leap)   |2                    |May                  |                       |10     |5    | |
|124(-1 for non leap)   |3                    |May                  |                       |11     |5    | |
|125(-1 for non leap)   |4                    |May                  |                       |12     |5    | |
|126(-1 for non leap)   |5                    |May                  |                       |13     |5    | |
|127(-1 for non leap)   |6                    |May                  |                       |14     |5    | |
|128(-1 for non leap)   |7                    |May                  |                       |15     |5    | |
|129(-1 for non leap)   |8                    |May                  |                       |16     |5    | |
|130(-1 for non leap)   |9                    |May                  |                       |17     |5    | |
|131(-1 for non leap)   |10                   |May                  |                       |18     |5    | |
|132(-1 for non leap)   |11                   |May                  |                       |19     |5    | |
|133(-1 for non leap)   |12                   |May                  |                       |20     |5    | |
|134(-1 for non leap)   |13                   |May                  |                       |21     |5    | |
|135(-1 for non leap)   |14                   |May                  |                       |22     |5    | |
|136(-1 for non leap)   |15                   |May                  |                       |23     |5    | |
|137(-1 for non leap)   |16                   |May                  |                       |24     |5    | |
|138(-1 for non leap)   |17                   |May                  |                       |25     |5    | |
|139(-1 for non leap)   |18                   |May                  |                       |26     |5    | |
|140(-1 for non leap)   |19                   |May                  |                       |27     |5    | |
|141(-1 for non leap)   |20                   |May                  |                       |28     |5    | |
|142(-1 for non leap)   |21                   |May                  |                       |29     |5    | |
|143(-1 for non leap)   |22                   |May                  |                       |30     |5    | |
|144(-1 for non leap)   |23                   |May                  |                       |1      |6    | |
|145(-1 for non leap)   |24                   |May                  |                       |2      |6    | |
|146(-1 for non leap)   |25                   |May                  |                       |3      |6    | |
|147(-1 for non leap)   |26                   |May                  |                       |4      |6    | |
|148(-1 for non leap)   |27                   |May                  |                       |5      |6    | |
|149(-1 for non leap)   |28                   |May                  |                       |6      |6    | |
|150(-1 for non leap)   |29                   |May                  |                       |7      |6    | |
|151(-1 for non leap)   |30                   |May                  |                       |8      |6    | |
|152(-1 for non leap)   |31                   |May                  |                       |9      |6    | |
|153(-1 for non leap)   |1                    |June                 |                       |10     |6    | |
|154(-1 for non leap)   |2                    |June                 |                       |11     |6    | |
|155(-1 for non leap)   |3                    |June                 |                       |12     |6    | |
|156(-1 for non leap)   |4                    |June                 |                       |13     |6    | |
|157(-1 for non leap)   |5                    |June                 |                       |14     |6    | |
|158(-1 for non leap)   |6                    |June                 |                       |15     |6    | |
|159(-1 for non leap)   |7                    |June                 |                       |16     |6    | |
|160(-1 for non leap)   |8                    |June                 |                       |17     |6    | |
|161(-1 for non leap)   |9                    |June                 |                       |18     |6    | |
|162(-1 for non leap)   |10                   |June                 |                       |19     |6    | |
|163(-1 for non leap)   |11                   |June                 |                       |20     |6    | |
|164(-1 for non leap)   |12                   |June                 |                       |21     |6    | |
|165(-1 for non leap)   |13                   |June                 |                       |22     |6    | |
|166(-1 for non leap)   |14                   |June                 |                       |23     |6    | |
|167(-1 for non leap)   |15                   |June                 |                       |24     |6    | |
|168(-1 for non leap)   |16                   |June                 |                       |25     |6    | |
|169(-1 for non leap)   |17                   |June                 |                       |26     |6    | |
|170(-1 for non leap)   |18                   |June                 |                       |27     |6    | |
|171(-1 for non leap)   |19                   |June                 |                       |28     |6    | |
|172(-1 for non leap)   |20                   |June                 |                       |29     |6    | |
|173(-1 for non leap)   |21                   |June                 |                       |30     |6    | |
|                       |N/A                  |N/A                  |                       |0      |7    | [Leap day](https://github.com/abozhilov/bgcalendar/blob/master/bgcalendar.js#L9) implemented [here](https://github.com/abozhilov/bgcalendar/blob/master/bgcalendar.js#L100). Explanation: [Всяка четвърта година е високосна – от 366 дни. Тя се различава от обикновената, единствено по това, че след шестия месец съдържа втори нулев ден, наречен Ени-Джитем.](https://tretooko.com/articles/astrologiya/634-drevniyat-prabalgarski-kalendar-prabalgarski-zodiak) for leap years this needs to be -1
|174 (-1 for non leap)  |22                   |June                 |                       |1      |7    | |
|175 (-1 for non leap)  |23                   |June                 |                       |2      |7    | |
|176 (-1 for non leap)  |24                   |June                 |                       |3      |7    | |
|177 (-1 for non leap)  |25                   |June                 |                       |4      |7    | |
|178 (-1 for non leap)  |26                   |June                 |                       |5      |7    | |
|179 (-1 for non leap)  |27                   |June                 |                       |6      |7    | |
|180 (-1 for non leap)  |28                   |June                 |                       |7      |7    | |
|181 (-1 for non leap)  |29                   |June                 |                       |8      |7    | |
|182 (-1 for non leap)  |30                   |June                 |                       |9      |7    | |
|183 (-1 for non leap)  |1                    |July                 |                       |10     |7    | |
|184 (-1 for non leap)  |2                    |July                 |                       |11     |7    | |
|185 (-1 for non leap)  |3                    |July                 |                       |12     |7    | |
|186 (-1 for non leap)  |4                    |July                 |                       |13     |7    | |
|187 (-1 for non leap)  |5                    |July                 |                       |14     |7    | |
|188 (-1 for non leap)  |6                    |July                 |                       |15     |7    | |
|189 (-1 for non leap)  |7                    |July                 |                       |16     |7    | |
|190 (-1 for non leap)  |8                    |July                 |                       |17     |7    | |
|191 (-1 for non leap)  |9                    |July                 |                       |18     |7    | |
|192 (-1 for non leap)  |10                   |July                 |                       |19     |7    | |
|193 (-1 for non leap)  |11                   |July                 |                       |20     |7    | |
|194 (-1 for non leap)  |12                   |July                 |                       |21     |7    | |
|195 (-1 for non leap)  |13                   |July                 |                       |22     |7    | |
|196 (-1 for non leap)  |14                   |July                 |                       |23     |7    | |
|197 (-1 for non leap)  |15                   |July                 |                       |24     |7    | |
|198 (-1 for non leap)  |16                   |July                 |                       |25     |7    | |
|199 (-1 for non leap)  |17                   |July                 |                       |26     |7    | |
|200 (-1 for non leap)  |18                   |July                 |                       |27     |7    | |
|201 (-1 for non leap)  |19                   |July                 |                       |28     |7    | |
|202 (-1 for non leap)  |20                   |July                 |                       |29     |7    | |
|203 (-1 for non leap)  |21                   |July                 |                       |30     |7    | |
|204 (-1 for non leap)  |22                   |July                 |                       |31     |7    | |
|205 (-1 for non leap)  |23                   |July                 |                       |1      |8    | |
|206 (-1 for non leap)  |24                   |July                 |                       |2      |8    | |
|207 (-1 for non leap)  |25                   |July                 |                       |3      |8    | |
|208 (-1 for non leap)  |26                   |July                 |                       |4      |8    | |
|209 (-1 for non leap)  |27                   |July                 |                       |5      |8    | |
|210 (-1 for non leap)  |28                   |July                 |                       |6      |8    | |
|211 (-1 for non leap)  |29                   |July                 |                       |7      |8    | |
|212 (-1 for non leap)  |30                   |July                 |                       |8      |8    | |
|213 (-1 for non leap)  |31                   |July                 |                       |9      |8    | |
|214 (-1 for non leap)  |1                    |August               |                       |10     |8    | |
|215 (-1 for non leap)  |2                    |August               |                       |11     |8    | |
|216 (-1 for non leap)  |3                    |August               |                       |12     |8    | |
|217 (-1 for non leap)  |4                    |August               |                       |13     |8    | |
|218 (-1 for non leap)  |5                    |August               |                       |14     |8    | |
|219 (-1 for non leap)  |6                    |August               |                       |15     |8    | |
|220 (-1 for non leap)  |7                    |August               |                       |16     |8    | |
|221 (-1 for non leap)  |8                    |August               |                       |17     |8    | |
|222 (-1 for non leap)  |9                    |August               |                       |18     |8    | |
|223 (-1 for non leap)  |10                   |August               |                       |19     |8    | |
|224 (-1 for non leap)  |11                   |August               |                       |20     |8    | |
|225 (-1 for non leap)  |12                   |August               |                       |21     |8    | |
|226 (-1 for non leap)  |13                   |August               |                       |22     |8    | |
|227 (-1 for non leap)  |14                   |August               |                       |23     |8    | |
|228 (-1 for non leap)  |15                   |August               |                       |24     |8    | |
|229 (-1 for non leap)  |16                   |August               |                       |25     |8    | |
|230 (-1 for non leap)  |17                   |August               |                       |26     |8    | |
|231 (-1 for non leap)  |18                   |August               |                       |27     |8    | |
|232 (-1 for non leap)  |19                   |August               |                       |28     |8    | |
|233 (-1 for non leap)  |20                   |August               |                       |29     |8    | |
|234 (-1 for non leap)  |21                   |August               |                       |30     |8    | |
|235 (-1 for non leap)  |22                   |August               |                       |1      |9    | |
|236 (-1 for non leap)  |23                   |August               |                       |2      |9    | |
|237 (-1 for non leap)  |24                   |August               |                       |3      |9    | |
|238 (-1 for non leap)  |25                   |August               |                       |4      |9    | |
|239 (-1 for non leap)  |26                   |August               |                       |5      |9    | |
|240 (-1 for non leap)  |27                   |August               |                       |6      |9    | |
|241 (-1 for non leap)  |28                   |August               |                       |7      |9    | |
|242 (-1 for non leap)  |29                   |August               |                       |8      |9    | |
|243 (-1 for non leap)  |30                   |August               |                       |9      |9    | |
|244 (-1 for non leap)  |31                   |August               |                       |10     |9    | |
|245 (-1 for non leap)  |1                    |September            |                       |11     |9    | |
|246 (-1 for non leap)  |2                    |September            |                       |12     |9    | |
|247 (-1 for non leap)  |3                    |September            |                       |13     |9    | |
|248 (-1 for non leap)  |4                    |September            |                       |14     |9    | |
|249 (-1 for non leap)  |5                    |September            |                       |15     |9    | |
|250 (-1 for non leap)  |6                    |September            |                       |16     |9    | |
|251 (-1 for non leap)  |7                    |September            |                       |17     |9    | |
|252 (-1 for non leap)  |8                    |September            |                       |18     |9    | |
|253 (-1 for non leap)  |9                    |September            |                       |19     |9    | |
|254 (-1 for non leap)  |10                   |September            |                       |20     |9    | |
|255 (-1 for non leap)  |11                   |September            |                       |21     |9    | |
|256 (-1 for non leap)  |12                   |September            |                       |22     |9    | |
|257 (-1 for non leap)  |13                   |September            |                       |23     |9    | |
|258 (-1 for non leap)  |14                   |September            |                       |24     |9    | |
|259 (-1 for non leap)  |15                   |September            |                       |25     |9    | |
|260 (-1 for non leap)  |16                   |September            |                       |26     |9    | |
|261 (-1 for non leap)  |17                   |September            |                       |27     |9    | |
|262 (-1 for non leap)  |18                   |September            |                       |28     |9    | |
|263 (-1 for non leap)  |19                   |September            |                       |29     |9    | |
|264 (-1 for non leap)  |20                   |September            |                       |30     |9    | |
|265 (-1 for non leap)  |21                   |September            |                       |1      |10   | |
|266 (-1 for non leap)  |22                   |September            |                       |2      |10   | |
|267 (-1 for non leap)  |23                   |September            |                       |3      |10   | |
|268 (-1 for non leap)  |24                   |September            |                       |4      |10   | |
|269 (-1 for non leap)  |25                   |September            |                       |5      |10   | |
|270 (-1 for non leap)  |26                   |September            |                       |6      |10   | |
|271 (-1 for non leap)  |27                   |September            |                       |7      |10   | |
|272 (-1 for non leap)  |28                   |September            |                       |8      |10   | |
|273 (-1 for non leap)  |29                   |September            |                       |9      |10   | |
|274 (-1 for non leap)  |30                   |September            |                       |10     |10   | |
|275 (-1 for non leap)  |1                    |October              |                       |11     |10   | |
|276 (-1 for non leap)  |2                    |October              |                       |12     |10   | |
|277 (-1 for non leap)  |3                    |October              |                       |13     |10   | |
|278 (-1 for non leap)  |4                    |October              |                       |14     |10   | |
|279 (-1 for non leap)  |5                    |October              |                       |15     |10   | |
|280 (-1 for non leap)  |6                    |October              |                       |16     |10   | |
|281 (-1 for non leap)  |7                    |October              |                       |17     |10   | |
|282 (-1 for non leap)  |8                    |October              |                       |18     |10   | |
|283 (-1 for non leap)  |9                    |October              |                       |19     |10   | |
|284 (-1 for non leap)  |10                   |October              |                       |20     |10   | |
|285 (-1 for non leap)  |11                   |October              |                       |21     |10   | |
|286 (-1 for non leap)  |12                   |October              |                       |22     |10   | |
|287 (-1 for non leap)  |13                   |October              |                       |23     |10   | |
|288 (-1 for non leap)  |14                   |October              |                       |24     |10   | |
|289 (-1 for non leap)  |15                   |October              |                       |25     |10   | |
|290 (-1 for non leap)  |16                   |October              |                       |26     |10   | |
|291 (-1 for non leap)  |17                   |October              |                       |27     |10   | |
|292 (-1 for non leap)  |18                   |October              |                       |28     |10   | |
|293 (-1 for non leap)  |19                   |October              |                       |29     |10   | |
|294 (-1 for non leap)  |20                   |October              |                       |30     |10   | |
|295 (-1 for non leap)  |21                   |October              |                       |31     |10   | |
|296 (-1 for non leap)  |22                   |October              |                       |1      |11   | |
|297 (-1 for non leap)  |23                   |October              |                       |2      |11   | |
|298 (-1 for non leap)  |24                   |October              |                       |3      |11   | |
|299 (-1 for non leap)  |25                   |October              |                       |4      |11   | |
|300 (-1 for non leap)  |26                   |October              |                       |5      |11   | |
|301 (-1 for non leap)  |27                   |October              |                       |6      |11   | |
|302 (-1 for non leap)  |28                   |October              |                       |7      |11   | |
|303 (-1 for non leap)  |29                   |October              |                       |8      |11   | |
|304 (-1 for non leap)  |30                   |October              |                       |9      |11   | |
|305 (-1 for non leap)  |31                   |October              |                       |10     |11   | |
|306 (-1 for non leap)  |1                    |November             |                       |11     |11   | |
|307 (-1 for non leap)  |2                    |November             |                       |12     |11   | |
|308 (-1 for non leap)  |3                    |November             |                       |13     |11   | |
|309 (-1 for non leap)  |4                    |November             |                       |14     |11   | |
|310 (-1 for non leap)  |5                    |November             |                       |15     |11   | |
|311 (-1 for non leap)  |6                    |November             |                       |16     |11   | |
|312 (-1 for non leap)  |7                    |November             |                       |17     |11   | |
|313 (-1 for non leap)  |8                    |November             |                       |18     |11   | |
|314 (-1 for non leap)  |9                    |November             |                       |19     |11   | |
|315 (-1 for non leap)  |10                   |November             |                       |20     |11   | |
|316 (-1 for non leap)  |11                   |November             |                       |21     |11   | |
|317 (-1 for non leap)  |12                   |November             |                       |22     |11   | |
|318 (-1 for non leap)  |13                   |November             |                       |23     |11   | |
|319 (-1 for non leap)  |14                   |November             |                       |24     |11   | |
|320 (-1 for non leap)  |15                   |November             |                       |25     |11   | |
|321 (-1 for non leap)  |16                   |November             |                       |26     |11   | |
|322 (-1 for non leap)  |17                   |November             |                       |27     |11   | |
|323 (-1 for non leap)  |18                   |November             |                       |28     |11   | |
|324 (-1 for non leap)  |19                   |November             |                       |29     |11   | |
|325 (-1 for non leap)  |20                   |November             |                       |30     |11   | |
|326 (-1 for non leap)  |21                   |November             |                       |1      |12   | |
|327 (-1 for non leap)  |22                   |November             |                       |2      |12   | |
|328 (-1 for non leap)  |23                   |November             |                       |3      |12   | |
|329 (-1 for non leap)  |24                   |November             |                       |4      |12   | |
|330 (-1 for non leap)  |25                   |November             |                       |5      |12   | |
|331 (-1 for non leap)  |26                   |November             |                       |6      |12   | |
|332 (-1 for non leap)  |27                   |November             |                       |7      |12   | |
|333 (-1 for non leap)  |28                   |November             |                       |8      |12   | |
|334 (-1 for non leap)  |29                   |November             |                       |9      |12   | |
|335 (-1 for non leap)  |30                   |November             |                       |10     |12   | |
|336 (-1 for non leap)  |1                    |December             |                       |11     |12   | |
|337 (-1 for non leap)  |2                    |December             |                       |12     |12   | |
|338 (-1 for non leap)  |3                    |December             |                       |13     |12   | |
|339 (-1 for non leap)  |4                    |December             |                       |14     |12   | |
|340 (-1 for non leap)  |5                    |December             |                       |15     |12   | |
|341 (-1 for non leap)  |6                    |December             |                       |16     |12   | |
|342 (-1 for non leap)  |7                    |December             |                       |17     |12   | |
|343 (-1 for non leap)  |8                    |December             |                       |18     |12   | |
|344 (-1 for non leap)  |9                    |December             |                       |19     |12   | |
|345 (-1 for non leap)  |10                   |December             |                       |20     |12   | |
|346 (-1 for non leap)  |11                   |December             |                       |21     |12   | |
|347 (-1 for non leap)  |12                   |December             |                       |22     |12   | |
|348 (-1 for non leap)  |13                   |December             |                       |23     |12   | |
|349 (-1 for non leap)  |14                   |December             |                       |24     |12   | |
|350 (-1 for non leap)  |15                   |December             |                       |25     |12   | |
|351 (-1 for non leap)  |16                   |December             |                       |26     |12   | |
|352 (-1 for non leap)  |17                   |December             |                       |27     |12   | |
|353 (-1 for non leap)  |18                   |December             |                       |28     |12   | |
|354 (-1 for non leap)  |19                   |December             |                       |29     |12   | |
|355 (-1 for non leap)  |20                   |December             |                       |30     |12   | |
|356 (-1 for non leap)  |21                   |December             |                       |0      |0    | [Този ден – Игнажден, Еднажден - не участвал в никой месец, не е включен и в никоя седмица. Той е бил самостоятелна календарна единица – нулев ден, Ени-Алем. Сега се нарича Енин Ден или Eднажден.](https://tretooko.com/articles/astrologiya/634-drevniyat-prabalgarski-kalendar-prabalgarski-zodiak) (comment: usually we selebrate this on 20th of december I don't know why this is implemented this way. Maybe it is wrong and the Bulgarian year should start on 20.12 Gregorian. It appears the shortest day of the year changes depending on the year. Here is an explanation in [Wikipedia](https://bg.wikipedia.org/wiki/%D0%A1%D0%BB%D1%8A%D0%BD%D1%86%D0%B5%D1%81%D1%82%D0%BE%D0%B5%D0%BD%D0%B5)) Also there is some logic regarding the start of month 12. If it is a leap year the first day is `Високосен Ден` else this is also day 0 which is `Нова година`|
|357 (-1 for non leap)  |22                   |December             |                       |1      |1    | |
|358 (-1 for non leap)  |23                   |December             |                       |2      |1    | |
|359 (-1 for non leap)  |24                   |December             |                       |3      |1    | |
|360 (-1 for non leap)  |25                   |December             |                       |4      |1    | |
|361 (-1 for non leap)  |26                   |December             |                       |5      |1    | |
|362 (-1 for non leap)  |27                   |December             |                       |6      |1    | |
|363 (-1 for non leap)  |28                   |December             |                       |7      |1    | |
|364 (-1 for non leap)  |29                   |December             |                       |8      |1    | |
|365 (-1 for non leap)  |30                   |December             |                       |9      |1    | |
|366 (-1 for non leap)  |31                   |December             |                       |

**Comment by NewestUser** [comment]
I think we now can understand the base logic for calculating the dates (without some edge cases)

Example:

The year **30/01/2019** in the Gregorian calendar would be **08/02/6787** or **8 Тутом, 6787 Докс**

The way this is calculated is the 30th day of the Gregorian year is looked up against the table above. It corresponds to the 8th day of the 2nd month in the BG calendar.
The year is calculated by adding the difference in years to the Gregorian year or 2019+4768=6787

The name of the 2nd month in the BG calendar is **Тутом** and the year type is  **Докс** which is calculated with mod 12 (because there are 12 different cycles in the BG calendar) 6786%12=7 which corresponds to the 7th cycle type **Докс**.

@rositsabodurova This should be enough for an MVP. If you have questions feel free to comment or ping me.

**Comment by rositsabodurova** [comment]
Hi Everyone!
I have a first draft of a class implementing the date conversion logic, here is what is is showing on the index page for today:
![image](https://user-images.githubusercontent.com/47860173/66159817-73acc800-e631-11e9-9b2a-d2a43b5e0e5f.png)
This is a day difference from the one shown on the[ original site:](http://calendar.samoistina.com/)
![image](https://user-images.githubusercontent.com/47860173/66159994-d0a87e00-e631-11e9-9336-3c4b0baed5bd.png)

I have also noticed that two consecutive dates of the contemporary calendar are the same in the Bulgarian one (30.03.2019 and 31.03.2019 are both 7 Твирем, 6787 Докс) @NewestUser, am I missing something? 

Maybe I should open a merge request?

**Comment by NewestUser** [comment]
I haven't noticed that @rositsabodurova . Maybe there is a problem with the implementation.
You can open a PR, after code review we can merge your implementation and on a second iteration we will figure out most of the bugs. 
We can afford to do that as we are not on Production and don't have any users :)
